"""
REST API for Predictive Occupancy Modeling
=========================================

This module defines a small FastAPI application that exposes a REST
interface for training a probability‑based occupancy model and
querying its predictions at runtime.  It is designed for deployment
on resource‑constrained IoT or edge devices so that Building
Automation Systems (BAS) can request occupancy forecasts via HTTP.

Endpoints
---------

* **POST /train** – Train a model from a CSV file on disk.  The
  request body must include the path to the CSV as well as optional
  parameters controlling the names of the timestamp and occupancy
  columns, the timezone, the cleaning deadband and the probability
  threshold.  Training computes a probability table and a binary
  schedule matrix.  It also performs stationarity tests on the
  raw occupancy counts and returns their p‑values for reference.

* **GET /state** – Query the current occupancy state and next
  transition.  Clients can optionally supply a timestamp (ISO
  8601) via the ``at`` query parameter.  If omitted, the server
  uses its current time.  The response includes the reference time
  (in UTC), whether the zone is currently occupied or not, and
  information about the next transition (START or END), the number
  of minutes until that transition and the exact transition time.

* **GET /schedule** – Retrieve the full weekly schedule matrix
  generated by the most recent training.  The response includes
  ``step_minutes`` (the slot size), a list of row indices (fractional
  hours) and a nested list representing the schedule for each slot
  and day.  A value of 1 indicates occupied; 0 indicates unoccupied.

The application maintains its model state in memory.  If a client
issues a query before training, a 400 error is returned.  To train
a model, the CSV must reside inside the container or be accessible
via a mounted volume.

Example
-------

Assuming the container has been built and is running on port 8000,
first train the model:

```
curl -X POST http://localhost:8000/train \
  -H "Content-Type: application/json" \
  -d '{"data_path": "data/occupancy_sample.csv"}'
```

Then query the current state:

```
curl http://localhost:8000/state
```

Or retrieve the schedule as JSON:

```
curl http://localhost:8000/schedule
```
"""

from __future__ import annotations

import datetime as _dt
from typing import Optional, Any, Dict, List

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field
import pandas as pd

from .data_processing import load_occupancy_data, clean_occupancy_counts
from .baseline_models import infer_step_minutes, build_probability_table, export_probability_schedule
from .stationarity import adf_stationary, kpss_stationary


class TrainRequest(BaseModel):
    """Request body for the /train endpoint.

    Attributes
    ----------
    data_path : str
        Path to the CSV file containing occupancy data.  This file
        must be accessible from within the container.
    time_col : str, default "time"
        Name of the timestamp column in the CSV.
    occ_col : str, default "occ"
        Name of the occupancy count column in the CSV.
    tz : str, default "UTC"
        Timezone used to localise timestamps.  If the CSV contains
        naive timestamps they will be interpreted as UTC and then
        converted to this timezone.
    deadband : float, default 1.0
        Threshold applied during cleaning.  Counts less than or equal
        to this value are treated as unoccupied.
    prob_threshold : float, default 0.5
        Decision threshold used when converting occupancy probabilities
        into binary values for the exported schedule.
    """

    data_path: str = Field(..., description="Path to the CSV file to train on")
    time_col: str = Field("time", description="Name of the timestamp column")
    occ_col: str = Field("occ", description="Name of the occupancy count column")
    tz: str = Field("UTC", description="Timezone for localising timestamps")
    deadband: float = Field(1.0, description="Deadband threshold for cleaning")
    prob_threshold: float = Field(0.5, description="Probability threshold for schedule generation")


class TransitionInfo(BaseModel):
    """Information about the next occupancy transition."""

    type: str = Field(..., description="START if transitioning to occupied, END if transitioning to unoccupied")
    in_minutes: int = Field(..., description="Number of minutes until the transition")
    at: str = Field(..., description="ISO 8601 timestamp when the transition occurs (UTC)")


class StateResponse(BaseModel):
    """Response body for the /state endpoint."""

    reference_time: str = Field(..., description="The time the state was evaluated (UTC)")
    current_state: str = Field(..., description="OCCUPIED or UNOCCUPIED")
    probability: float = Field(..., description="Historical probability of occupancy for the current time slot")
    next_transition: TransitionInfo


class ScheduleResponse(BaseModel):
    """Response body for the /schedule endpoint."""

    step_minutes: int = Field(..., description="The slot length in minutes")
    hours: List[float] = Field(..., description="Row index representing hours past midnight (fractional)")
    schedule: List[List[int]] = Field(..., description="Nested list of occupancy predictions for each day")


class ModelState:
    """Holds the trained model components in memory."""

    def __init__(
        self,
        step_minutes: int,
        prob_threshold: float,
        tz: str,
        prob_table: pd.DataFrame,
        schedule_matrix: pd.DataFrame,
        hour_index: List[float],
    ) -> None:
        self.step_minutes = step_minutes
        self.prob_threshold = prob_threshold
        self.tz = tz
        self.prob_table = prob_table  # columns: dow, slot, p_occ
        self.schedule_matrix = schedule_matrix  # index: fractional hour, columns: dow (0–6)
        self.hour_index = hour_index  # list of fractional hours corresponding to schedule rows

    def get_probability(self, dow: int, slot: int) -> float:
        """Return the historical probability for a given day and slot.

        Parameters
        ----------
        dow : int
            Day of week (0=Monday).
        slot : int
            Minute of day rounded down to the nearest slot boundary.

        Returns
        -------
        float
            Probability of occupancy.  If the slot is unseen in the
            training data, returns 0.0.
        """
        rec = self.prob_table[(self.prob_table["dow"] == dow) & (self.prob_table["slot"] == slot)]
        if not rec.empty:
            return float(rec.iloc[0]["p_occ"])
        return 0.0

    def get_schedule_value(self, dow: int, slot: int) -> int:
        """Return the binary schedule value (0 or 1) for a given day and slot.

        Parameters
        ----------
        dow : int
            Day of week (0=Monday).
        slot : int
            Minute of day rounded down to the nearest slot boundary.

        Returns
        -------
        int
            1 if occupied, 0 if unoccupied.  If the slot is unseen,
            defaults to 0.
        """
        hour = slot / 60.0
        try:
            val = self.schedule_matrix.loc[hour, dow]
            return int(val)
        except Exception:
            return 0


app = FastAPI(
    title="Predictive Occupancy Modeling API",
    description=(
        "Train and query a probability‑based occupancy model from time‑series data. "
        "Designed for deployment on IoT or edge devices running a BAS."
    ),
    version="0.2.0",
)

# Global model state.  Initially None until training occurs.
_model_state: Optional[ModelState] = None


@app.post("/train")
def train_model(request: TrainRequest) -> Dict[str, Any]:
    """Train a probability‑based occupancy model.

    This endpoint loads a CSV from disk, cleans the occupancy counts,
    calculates the empirical probability of occupancy for each slot,
    constructs a binary schedule, and stores the results in memory.
    It also performs Augmented Dickey–Fuller (ADF) and KPSS tests on
    the raw occupancy signal to provide feedback on whether the
    series appears stationary.

    Returns
    -------
    dict
        A dictionary containing the p‑values and stationarity flags
        from the ADF and KPSS tests, the inferred step size in
        minutes, and the number of records processed.
    """
    global _model_state

    # Load raw data
    try:
        df = load_occupancy_data(
            request.data_path,
            time_col=request.time_col,
            occ_col=request.occ_col,
            parse_dates=True,
            tz=request.tz,
            rename_columns=True,
        )
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Failed to load data: {exc}")

    # Clean counts and derive binary flag
    df_clean = clean_occupancy_counts(df, occ_col="occ", deadband=request.deadband, make_binary=True)

    # Infer sampling step and build probability table
    step_minutes = infer_step_minutes(df_clean, time_col="time")
    prob_table = build_probability_table(
        df_clean,
        occ_threshold=0.0,
        step_minutes=step_minutes,
        occ_col="clean_count",
    )

    # Build schedule matrix (binary) and capture the hour index
    matrix = export_probability_schedule(
        prob_table,
        output_path=None,
        prob_threshold=request.prob_threshold,
        step_minutes=step_minutes,
    )
    hour_index = list(matrix.index.values.tolist())

    # Store model state
    _model_state = ModelState(
        step_minutes=step_minutes,
        prob_threshold=request.prob_threshold,
        tz=request.tz,
        prob_table=prob_table,
        schedule_matrix=matrix,
        hour_index=hour_index,
    )

    # Run stationarity tests on the raw occupancy signal (not cleaned)
    adf_stat, adf_p, _ = adf_stationary(df["occ"].values)
    kpss_stat, kpss_p, _ = kpss_stationary(df["occ"].values)

    return {
        "message": "Model trained successfully",
        "records": len(df),
        "step_minutes": step_minutes,
        "adf_p": adf_p,
        "adf_stationary": bool(adf_stat),
        "kpss_p": kpss_p,
        "kpss_stationary": bool(kpss_stat),
    }


@app.get("/state", response_model=StateResponse)
def get_state(at: Optional[str] = Query(None, description="ISO 8601 timestamp (UTC) to evaluate. Defaults to now.")) -> Any:
    """Return the current occupancy state and next transition.

    Parameters
    ----------
    at : str, optional
        ISO 8601 timestamp in UTC at which to evaluate the state.  If
        omitted the server's current time is used.

    Returns
    -------
    StateResponse
        Structured JSON containing the reference time, current state,
        probability of occupancy and information about the next
        transition.
    """
    global _model_state
    if _model_state is None:
        raise HTTPException(status_code=400, detail="Model has not been trained yet")

    # Parse the provided timestamp or use now
    if at is not None:
        try:
            ref_dt = _dt.datetime.fromisoformat(at.replace("Z", "+00:00"))
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid ISO 8601 timestamp")
    else:
        ref_dt = _dt.datetime.utcnow().replace(tzinfo=_dt.timezone.utc)

    # Convert to the model's timezone for slot calculation
    try:
        # Use zoneinfo module (Python 3.9+) for timezone conversions
        from zoneinfo import ZoneInfo  # type: ignore

        tzinfo = ZoneInfo(_model_state.tz)
    except Exception:
        tzinfo = None
    if tzinfo is not None:
        ref_local = ref_dt.astimezone(tzinfo)
    else:
        ref_local = ref_dt
    # Determine day of week and slot boundaries
    dow = ref_local.weekday()
    minute_of_day = ref_local.hour * 60 + ref_local.minute
    step = _model_state.step_minutes
    slot = (minute_of_day // step) * step
    # Current occupancy probability and state
    prob = _model_state.get_probability(dow, slot)
    curr_state = "OCCUPIED" if prob >= _model_state.prob_threshold else "UNOCCUPIED"
    # Find next transition by iterating over future slots (max one week)
    next_state = None
    next_minutes = 0
    next_dt_local = ref_local
    current_binary = 1 if curr_state == "OCCUPIED" else 0
    # Determine schedule value at current time
    curr_schedule_value = _model_state.get_schedule_value(dow, slot)
    for i in range(1, (7 * 24 * 60) // step + 1):
        # Compute future slot index and day of week
        minutes_ahead = i * step
        future_minute = minute_of_day + minutes_ahead
        future_dow = (dow + (future_minute // (24 * 60))) % 7
        future_slot = (future_minute % (24 * 60) // step) * step
        future_value = _model_state.get_schedule_value(future_dow, future_slot)
        if future_value != curr_schedule_value:
            next_minutes = minutes_ahead
            next_dt_local = ref_local + _dt.timedelta(minutes=minutes_ahead)
            next_state = "START" if future_value == 1 else "END"
            break
    # If no transition found (rare), set next transition in one week
    if next_state is None:
        next_minutes = 7 * 24 * 60
        next_dt_local = ref_local + _dt.timedelta(minutes=next_minutes)
        # Invert state for next transition
        next_state = "END" if curr_state == "OCCUPIED" else "START"
    # Convert next_dt_local back to UTC string
    next_dt_utc = next_dt_local.astimezone(_dt.timezone.utc)
    return {
        "reference_time": ref_dt.astimezone(_dt.timezone.utc).isoformat(),
        "current_state": curr_state,
        "probability": prob,
        "next_transition": {
            "type": next_state,
            "in_minutes": int(next_minutes),
            "at": next_dt_utc.isoformat(),
        },
    }


@app.get("/schedule", response_model=ScheduleResponse)
def get_schedule() -> Any:
    """Return the full schedule matrix.

    Returns
    -------
    ScheduleResponse
        Contains the slot size in minutes, the row index of hours and
        a nested list representing the binary schedule for each day of
        the week.  A value of 1 means occupied, 0 means unoccupied.
    """
    global _model_state
    if _model_state is None:
        raise HTTPException(status_code=400, detail="Model has not been trained yet")
    # Convert the schedule matrix to nested lists for JSON serialisation
    matrix = _model_state.schedule_matrix
    # Ensure all seven columns are present in order
    cols = list(range(7))
    matrix = matrix.reindex(columns=cols, fill_value=0).fillna(0).astype(int)
    schedule_rows: List[List[int]] = matrix.values.tolist()
    return {
        "step_minutes": _model_state.step_minutes,
        "hours": _model_state.hour_index,
        "schedule": schedule_rows,
    }